// SPDX-License-Identifier: GPL-3.0-only
//
// Zenritme
// Copyright (C) 2026 rezky_nightky (oxyzenQ)

//! Embedded WAV assets and metadata.
//!
//! Four notification sounds are embedded at compile time via `include_bytes!`.
//! They were generated by `scripts/generate-sounds.py` using only the Python
//! standard library — no external samples, no copyrighted assets.

/// WAV files generated by `scripts/generate-sounds.py`, embedded at compile time.
const SOUND_START: &[u8] = include_bytes!("../../assets/sounds/start.wav");
const SOUND_PAUSE: &[u8] = include_bytes!("../../assets/sounds/pause.wav");
const SOUND_PHASE: &[u8] = include_bytes!("../../assets/sounds/phase.wav");
const SOUND_COMPLETE: &[u8] = include_bytes!("../../assets/sounds/complete.wav");

/// Environment variable names — per-event override keys.
pub(crate) const ENV_START: &str = "ZENRITME_SOUND_START";
pub(crate) const ENV_PAUSE: &str = "ZENRITME_SOUND_PAUSE";
pub(crate) const ENV_PHASE: &str = "ZENRITME_SOUND_PHASE";
pub(crate) const ENV_COMPLETE: &str = "ZENRITME_SOUND_COMPLETE";
pub(crate) const ENV_GLOBAL: &str = "ZENRITME_SOUND_FILE";

/// Returns the embedded WAV bytes for a given event.
pub fn embedded_sound(event: super::SoundEvent) -> &'static [u8] {
    match event {
        super::SoundEvent::Start => SOUND_START,
        super::SoundEvent::Pause => SOUND_PAUSE,
        super::SoundEvent::Phase => SOUND_PHASE,
        super::SoundEvent::Complete => SOUND_COMPLETE,
    }
}

/// Returns the per-event environment variable name.
pub fn env_var(event: super::SoundEvent) -> &'static str {
    match event {
        super::SoundEvent::Start => ENV_START,
        super::SoundEvent::Pause => ENV_PAUSE,
        super::SoundEvent::Phase => ENV_PHASE,
        super::SoundEvent::Complete => ENV_COMPLETE,
    }
}

/// Returns the default asset filename for a given event.
pub fn asset_filename(event: super::SoundEvent) -> &'static str {
    match event {
        super::SoundEvent::Start => "start.wav",
        super::SoundEvent::Pause => "pause.wav",
        super::SoundEvent::Phase => "phase.wav",
        super::SoundEvent::Complete => "complete.wav",
    }
}

/// All sound events in display order.
pub fn all_events() -> [super::SoundEvent; 4] {
    [
        super::SoundEvent::Start,
        super::SoundEvent::Pause,
        super::SoundEvent::Phase,
        super::SoundEvent::Complete,
    ]
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_sounds_non_empty() {
        assert!(!SOUND_START.is_empty(), "start.wav is empty");
        assert!(!SOUND_PAUSE.is_empty(), "pause.wav is empty");
        assert!(!SOUND_PHASE.is_empty(), "phase.wav is empty");
        assert!(!SOUND_COMPLETE.is_empty(), "complete.wav is empty");
    }

    #[test]
    fn embedded_sounds_are_valid_wav() {
        for (name, data) in [
            ("start", SOUND_START as &[u8]),
            ("pause", SOUND_PAUSE as &[u8]),
            ("phase", SOUND_PHASE as &[u8]),
            ("complete", SOUND_COMPLETE as &[u8]),
        ] {
            assert!(
                data.len() >= 44,
                "{}: WAV header too small ({} bytes)",
                name,
                data.len()
            );
            assert!(&data[0..4] == b"RIFF", "{}: missing RIFF header", name);
            assert!(&data[8..12] == b"WAVE", "{}: missing WAVE format", name);
        }
    }}
