// SPDX-License-Identifier: GPL-3.0-only
//
// Zenritme
// Copyright (C) 2026 Rezky Nightky

//! Built-in procedural sound system.
//!
//! Four notification sounds are embedded at compile time via `include_bytes!`.
//! They were generated by `scripts/generate-sounds.py` using only the Python
//! standard library — no external samples, no copyrighted assets.
//!
//! Resolution order (per event):
//!   1. Event-specific env var  (`ZENRITME_SOUND_START`, …)
//!   2. Global env var         (`ZENRITME_SOUND_FILE`)
//!   3. Built-in embedded WAV  (written to a temp file, played via `pw-play`)
//!
//! If `pw-play` is unavailable or playback fails, Zenritme falls back to
//! the terminal bell (`\x07`) and optionally the visual bell.

use std::io::{self, Write};
use std::process::{Command, Stdio};
use std::sync::OnceLock;

// ─── Sound event enum ────────────────────────────────────────────────────────

/// Notification sound events emitted during Zenritme operation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SoundEvent {
    /// Timer / session started.
    Start,
    /// Pause or resume toggled.
    Pause,
    /// Pomodoro phase switched.
    Phase,
    /// Timer / pomodoro fully completed.
    Complete,
}

// ─── Embedded sound data ──────────────────────────────────────────────────

/// WAV files generated by `scripts/generate-sounds.py`, embedded at compile time.
const SOUND_START: &[u8] = include_bytes!("../assets/sounds/start.wav");
const SOUND_PAUSE: &[u8] = include_bytes!("../assets/sounds/pause.wav");
const SOUND_PHASE: &[u8] = include_bytes!("../assets/sounds/phase.wav");
const SOUND_COMPLETE: &[u8] = include_bytes!("../assets/sounds/complete.wav");

// ─── Environment variable names ───────────────────────────────────────────

const ENV_START: &str = "ZENRITME_SOUND_START";
const ENV_PAUSE: &str = "ZENRITME_SOUND_PAUSE";
const ENV_PHASE: &str = "ZENRITME_SOUND_PHASE";
const ENV_COMPLETE: &str = "ZENRITME_SOUND_COMPLETE";
const ENV_GLOBAL: &str = "ZENRITME_SOUND_FILE";

// ─── Public query helpers (used by CLI --sound-test and tests) ─────────────

/// Returns the embedded WAV bytes for a given event.
pub fn embedded_sound(event: SoundEvent) -> &'static [u8] {
    match event {
        SoundEvent::Start => SOUND_START,
        SoundEvent::Pause => SOUND_PAUSE,
        SoundEvent::Phase => SOUND_PHASE,
        SoundEvent::Complete => SOUND_COMPLETE,
    }
}

/// Returns the per-event environment variable name.
pub fn env_var(event: SoundEvent) -> &'static str {
    match event {
        SoundEvent::Start => ENV_START,
        SoundEvent::Pause => ENV_PAUSE,
        SoundEvent::Phase => ENV_PHASE,
        SoundEvent::Complete => ENV_COMPLETE,
    }
}

/// Returns the default asset filename for a given event.
pub fn asset_filename(event: SoundEvent) -> &'static str {
    match event {
        SoundEvent::Start => "start.wav",
        SoundEvent::Pause => "pause.wav",
        SoundEvent::Phase => "phase.wav",
        SoundEvent::Complete => "complete.wav",
    }
}

/// All sound events in display order.
pub fn all_events() -> [SoundEvent; 4] {
    [
        SoundEvent::Start,
        SoundEvent::Pause,
        SoundEvent::Phase,
        SoundEvent::Complete,
    ]
}

// ─── Resolution logic ──────────────────────────────────────────────────────

/// Resolves the sound file path for an event.
///
/// Returns `Some(path)` when an external override exists (env var points to a
/// local file).  Returns `None` when the built-in embedded sound should be used.
pub fn resolve_sound_file(event: SoundEvent) -> Option<String> {
    // 1. Event-specific env override
    if let Ok(path) = std::env::var(env_var(event)) {
        return Some(path);
    }
    // 2. Global env override
    if let Ok(path) = std::env::var(ENV_GLOBAL) {
        return Some(path);
    }
    // 3. Built-in — no file path needed
    None
}

// ─── Temp-file cache for embedded sounds ────────────────────────────────────

/// Lazily-created temp directory for extracting embedded sounds.
fn temp_sound_dir() -> &'static std::path::PathBuf {
    static DIR: OnceLock<std::path::PathBuf> = OnceLock::new();
    DIR.get_or_init(|| {
        let dir = std::env::temp_dir().join(format!("zenritme-sounds-{}", std::process::id()));
        let _ = std::fs::create_dir_all(&dir);
        dir
    })
}

/// Ensures the embedded WAV for *event* exists as a temp file and returns its
/// path.  The file is written once per process and reused on subsequent plays.
fn ensure_embedded_file(event: SoundEvent) -> Option<std::path::PathBuf> {
    let data = embedded_sound(event);
    let path = temp_sound_dir().join(asset_filename(event));
    if !path.exists() && std::fs::write(&path, data).is_err() {
        return None;
    }
    Some(path)
}

// ─── Playback primitives ────────────────────────────────────────────────────

/// Tries to play a WAV file via `pw-play` (PipeWire / PulseAudio compat).
fn play_file_via_pw(path: &std::path::Path) -> bool {
    Command::new("pw-play")
        .arg(path)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .is_ok()
}

/// Plays a terminal bell character (`\x07`).
fn terminal_bell() {
    let mut stdout = io::stdout();
    let _ = stdout.write_all(b"\x07");
    let _ = stdout.flush();
}

/// Triggers a visual bell (brief screen flash via DEC private mode).
fn visual_bell() {
    let mut stdout = io::stdout();
    let _ = stdout.write_all(b"\x1b[?5h");
    let _ = stdout.flush();
    std::thread::sleep(std::time::Duration::from_millis(60));
    let _ = stdout.write_all(b"\x1b[?5l");
    let _ = stdout.flush();
}

// ─── Core play function ────────────────────────────────────────────────────

/// Plays a sound event.  Attempts (in order):
///
/// 1. External file via `pw-play`  (if an env override is set).
/// 2. Built-in embedded WAV via `pw-play`  (temp file extraction).
/// 3. Terminal bell fallback (`\x07`).
///
/// If `ZENRITME_VISUAL_BELL` is set, a visual bell flash is also triggered.
pub fn play_event(event: SoundEvent) {
    let played = if let Some(ref file) = resolve_sound_file(event) {
        play_file_via_pw(std::path::Path::new(file))
    } else if let Some(path) = ensure_embedded_file(event) {
        play_file_via_pw(&path)
    } else {
        false
    };

    if !played {
        terminal_bell();
    }

    if std::env::var("ZENRITME_VISUAL_BELL").is_ok() {
        visual_bell();
    }
}

// ─── Legacy multi-beep (kept for backward compat) ──────────────────────────

/// Plays the *Complete* sound `times` times with a short gap.  Kept for
/// backward compatibility; the main loop now uses `play_event` directly.
#[allow(dead_code)]
pub fn beep(times: u32) {
    let times = times.max(1);
    for i in 0..times {
        play_event(SoundEvent::Complete);
        if i + 1 < times {
            std::thread::sleep(std::time::Duration::from_millis(120));
        }
    }
}

// ─── --sound-test ───────────────────────────────────────────────────────────

/// Prints sound-system status and plays all four events in sequence.
pub fn sound_test() {
    println!("zenritme sound test (v{})", env!("CARGO_PKG_VERSION"));
    println!();

    // ── Per-event info ──────────────────────────────────────────────────────
    println!("Sound events and sources:");
    for event in all_events() {
        let env = env_var(event);
        let asset = asset_filename(event);
        match resolve_sound_file(event) {
            Some(ref file) => {
                println!(
                    "  {:9}  env={}, source={}",
                    format!("{:?}", event),
                    env,
                    file
                );
            }
            None => {
                println!(
                    "  {:9}  env={}, source=built-in ({})",
                    format!("{:?}", event),
                    env,
                    asset
                );
            }
        }
    }

    println!();

    // ── Override docs ──────────────────────────────────────────────────────
    println!("Override environment variables:");
    println!("  ZENRITME_SOUND_START     path to custom start sound");
    println!("  ZENRITME_SOUND_PAUSE     path to custom pause sound");
    println!("  ZENRITME_SOUND_PHASE     path to custom phase sound");
    println!("  ZENRITME_SOUND_COMPLETE  path to custom complete sound");
    println!("  ZENRITME_SOUND_FILE      global fallback for all events");
    println!("  ZENRITME_VISUAL_BELL=1   enable visual bell (screen flash)");
    println!();

    let global = match std::env::var(ENV_GLOBAL) {
        Ok(p) => format!("(global override: {})", p),
        Err(_) => "(none)".to_string(),
    };
    println!("Global override: {}", global);
    println!();

    // ── Playback demo ───────────────────────────────────────────────────────
    println!("Playing all events in sequence...");
    for event in all_events() {
        println!("  -> {:?}...", event);
        play_event(event);
        std::thread::sleep(std::time::Duration::from_millis(300));
    }
    println!();
    println!("Sound test complete.");
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Embedded data validity ──────────────────────────────────────────────

    #[test]
    fn embedded_sounds_non_empty() {
        assert!(!SOUND_START.is_empty(), "start.wav is empty");
        assert!(!SOUND_PAUSE.is_empty(), "pause.wav is empty");
        assert!(!SOUND_PHASE.is_empty(), "phase.wav is empty");
        assert!(!SOUND_COMPLETE.is_empty(), "complete.wav is empty");
    }

    #[test]
    fn embedded_sounds_are_valid_wav() {
        for (name, data) in [
            ("start", SOUND_START as &[u8]),
            ("pause", SOUND_PAUSE as &[u8]),
            ("phase", SOUND_PHASE as &[u8]),
            ("complete", SOUND_COMPLETE as &[u8]),
        ] {
            assert!(
                data.len() >= 44,
                "{}: WAV header too small ({} bytes)",
                name,
                data.len()
            );
            assert!(&data[0..4] == b"RIFF", "{}: missing RIFF header", name);
            assert!(&data[8..12] == b"WAVE", "{}: missing WAVE format", name);
        }
    }

    // ── Stable mapping ─────────────────────────────────────────────────────

    #[test]
    fn asset_filenames_stable() {
        assert_eq!(asset_filename(SoundEvent::Start), "start.wav");
        assert_eq!(asset_filename(SoundEvent::Pause), "pause.wav");
        assert_eq!(asset_filename(SoundEvent::Phase), "phase.wav");
        assert_eq!(asset_filename(SoundEvent::Complete), "complete.wav");
    }

    #[test]
    fn env_var_names_stable() {
        assert_eq!(env_var(SoundEvent::Start), "ZENRITME_SOUND_START");
        assert_eq!(env_var(SoundEvent::Pause), "ZENRITME_SOUND_PAUSE");
        assert_eq!(env_var(SoundEvent::Phase), "ZENRITME_SOUND_PHASE");
        assert_eq!(env_var(SoundEvent::Complete), "ZENRITME_SOUND_COMPLETE");
    }

    #[test]
    fn embedded_sound_maps_to_correct_data() {
        assert_eq!(embedded_sound(SoundEvent::Start), SOUND_START);
        assert_eq!(embedded_sound(SoundEvent::Pause), SOUND_PAUSE);
        assert_eq!(embedded_sound(SoundEvent::Phase), SOUND_PHASE);
        assert_eq!(embedded_sound(SoundEvent::Complete), SOUND_COMPLETE);
    }

    #[test]
    fn all_events_returns_four() {
        let events = all_events();
        assert_eq!(events.len(), 4);
        assert_eq!(events[0], SoundEvent::Start);
        assert_eq!(events[1], SoundEvent::Pause);
        assert_eq!(events[2], SoundEvent::Phase);
        assert_eq!(events[3], SoundEvent::Complete);
    }

    // ── Resolution (env var precedence) ────────────────────────────────────

    #[test]
    fn resolve_returns_none_when_no_env_set() {
        // Ensure no event-specific or global env vars interfere.
        std::env::remove_var(ENV_START);
        std::env::remove_var(ENV_GLOBAL);
        assert_eq!(resolve_sound_file(SoundEvent::Start), None);
    }

    #[test]
    fn resolve_event_env_over_global() {
        std::env::set_var("ZENRITME_SOUND_START", "/tmp/test-start.wav");
        std::env::set_var("ZENRITME_SOUND_FILE", "/tmp/test-global.wav");
        assert_eq!(
            resolve_sound_file(SoundEvent::Start),
            Some("/tmp/test-start.wav".to_string())
        );
        std::env::remove_var("ZENRITME_SOUND_START");
        std::env::remove_var("ZENRITME_SOUND_FILE");
    }

    #[test]
    fn resolve_global_fallback_when_no_event_env() {
        std::env::remove_var("ZENRITME_SOUND_PAUSE");
        std::env::set_var("ZENRITME_SOUND_FILE", "/tmp/test-global.wav");
        assert_eq!(
            resolve_sound_file(SoundEvent::Pause),
            Some("/tmp/test-global.wav".to_string())
        );
        std::env::remove_var("ZENRITME_SOUND_FILE");
    }

    #[test]
    fn resolve_other_events_unaffected_by_event_env() {
        std::env::remove_var("ZENRITME_SOUND_FILE");
        std::env::set_var("ZENRITME_SOUND_START", "/tmp/test-start.wav");
        // Phase should not be affected by the START override.
        assert_eq!(resolve_sound_file(SoundEvent::Phase), None);
        std::env::remove_var("ZENRITME_SOUND_START");
    }

    #[test]
    fn all_events_have_embeddings() {
        for event in all_events() {
            assert!(
                !embedded_sound(event).is_empty(),
                "{:?} embedded sound is empty",
                event
            );
        }
    }
}
