// SPDX-License-Identifier: GPL-3.0-only
//
// Zenritme
// Copyright (C) 2026 Rezky Nightky

//! Built-in procedural sound system.
//!
//! Four notification sounds are embedded at compile time via `include_bytes!`.
//! They were generated by `scripts/generate-sounds.py` using only the Python
//! standard library — no external samples, no copyrighted assets.
//!
//! Resolution order (per event):
//!   1. Event-specific env var  (`ZENRITME_SOUND_START`, …)
//!   2. Global env var         (`ZENRITME_SOUND_FILE`)
//!   3. Built-in embedded WAV  (written to a temp file, played via `pw-play`)
//!
//! If `pw-play` is unavailable or playback fails, Zenritme falls back to
//! the terminal bell (`\x07`) and optionally the visual bell.

use std::io::{self, Write};
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::OnceLock;

// ─── Sound profile ─────────────────────────────────────────────────────────

/// Sound profile controlling when notification sounds play.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SoundProfile {
    /// Normal sound behavior — all events produce notification sounds.
    Calm,
    /// All sounds suppressed (equivalent to `--mute`).
    Silent,
}

impl SoundProfile {
    /// Parse a profile name (case-insensitive).
    pub fn from_name(name: &str) -> Option<Self> {
        match name.to_lowercase().as_str() {
            "calm" => Some(SoundProfile::Calm),
            "silent" => Some(SoundProfile::Silent),
            _ => None,
        }
    }

    /// Returns `true` if all sounds should be suppressed.
    pub fn is_silent(self) -> bool {
        self == SoundProfile::Silent
    }

    /// Returns the string name for display.
    #[allow(dead_code)]
    pub fn as_str(self) -> &'static str {
        match self {
            SoundProfile::Calm => "calm",
            SoundProfile::Silent => "silent",
        }
    }
}

// ─── Sound event enum ────────────────────────────────────────────────────────

/// Notification sound events emitted during Zenritme operation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SoundEvent {
    /// Timer / session started.
    Start,
    /// Pause or resume toggled.
    Pause,
    /// Pomodoro phase switched.
    Phase,
    /// Timer / pomodoro fully completed.
    Complete,
}

// ─── Embedded sound data ──────────────────────────────────────────────────

/// WAV files generated by `scripts/generate-sounds.py`, embedded at compile time.
const SOUND_START: &[u8] = include_bytes!("../assets/sounds/start.wav");
const SOUND_PAUSE: &[u8] = include_bytes!("../assets/sounds/pause.wav");
const SOUND_PHASE: &[u8] = include_bytes!("../assets/sounds/phase.wav");
const SOUND_COMPLETE: &[u8] = include_bytes!("../assets/sounds/complete.wav");

// ─── Environment variable names ───────────────────────────────────────────

const ENV_START: &str = "ZENRITME_SOUND_START";
const ENV_PAUSE: &str = "ZENRITME_SOUND_PAUSE";
const ENV_PHASE: &str = "ZENRITME_SOUND_PHASE";
const ENV_COMPLETE: &str = "ZENRITME_SOUND_COMPLETE";
const ENV_GLOBAL: &str = "ZENRITME_SOUND_FILE";

// ─── Public query helpers (used by CLI --sound-test and tests) ─────────────

/// Returns the embedded WAV bytes for a given event.
pub fn embedded_sound(event: SoundEvent) -> &'static [u8] {
    match event {
        SoundEvent::Start => SOUND_START,
        SoundEvent::Pause => SOUND_PAUSE,
        SoundEvent::Phase => SOUND_PHASE,
        SoundEvent::Complete => SOUND_COMPLETE,
    }
}

/// Returns the per-event environment variable name.
pub fn env_var(event: SoundEvent) -> &'static str {
    match event {
        SoundEvent::Start => ENV_START,
        SoundEvent::Pause => ENV_PAUSE,
        SoundEvent::Phase => ENV_PHASE,
        SoundEvent::Complete => ENV_COMPLETE,
    }
}

/// Returns the default asset filename for a given event.
pub fn asset_filename(event: SoundEvent) -> &'static str {
    match event {
        SoundEvent::Start => "start.wav",
        SoundEvent::Pause => "pause.wav",
        SoundEvent::Phase => "phase.wav",
        SoundEvent::Complete => "complete.wav",
    }
}

/// All sound events in display order.
pub fn all_events() -> [SoundEvent; 4] {
    [
        SoundEvent::Start,
        SoundEvent::Pause,
        SoundEvent::Phase,
        SoundEvent::Complete,
    ]
}

// ─── Resolution logic ──────────────────────────────────────────────────────

/// Resolves the sound file path for an event.
///
/// Returns `Some(path)` when an external override exists (env var points to a
/// local file).  Returns `None` when the built-in embedded sound should be used.
pub fn resolve_sound_file(event: SoundEvent) -> Option<String> {
    // 1. Event-specific env override
    if let Ok(path) = std::env::var(env_var(event)) {
        return Some(path);
    }
    // 2. Global env override
    if let Ok(path) = std::env::var(ENV_GLOBAL) {
        return Some(path);
    }
    // 3. Built-in — no file path needed
    None
}

/// Returns a human-readable source description for an event's resolved sound.
pub fn sound_source(event: SoundEvent) -> String {
    match resolve_sound_file(event) {
        Some(ref path) => format!("override: {}", path),
        None => format!("built-in: {}", asset_filename(event)),
    }
}

// ─── Temp-file cache for embedded sounds ────────────────────────────────────

/// Lazily-created temp directory for extracting embedded sounds.
/// Path is project-specific and PID-specific to avoid conflicts.
fn temp_sound_dir() -> &'static std::path::PathBuf {
    static DIR: OnceLock<std::path::PathBuf> = OnceLock::new();
    DIR.get_or_init(|| {
        let dir = std::env::temp_dir().join(format!("zenritme-sounds-{}", std::process::id()));
        let _ = std::fs::create_dir_all(&dir);
        dir
    })
}

/// Ensures the embedded WAV for *event* exists as a temp file and returns its
/// path.  The file is written once per process and reused on subsequent plays.
fn ensure_embedded_file(event: SoundEvent) -> Option<std::path::PathBuf> {
    let data = embedded_sound(event);
    let path = temp_sound_dir().join(asset_filename(event));
    if !path.exists() && std::fs::write(&path, data).is_err() {
        return None;
    }
    Some(path)
}

/// Removes the temp sound directory created by this process.
///
/// Safe to call multiple times; no-op if the directory does not exist.
/// Only removes the PID-specific directory — never touches user files.
pub fn cleanup_temp_sounds() {
    static CLEANED: AtomicBool = AtomicBool::new(false);
    // Only clean once per process — guard against double-invocation.
    if CLEANED.swap(true, Ordering::Relaxed) {
        return;
    }
    let dir = std::env::temp_dir().join(format!("zenritme-sounds-{}", std::process::id()));
    if dir.exists() {
        let _ = std::fs::remove_dir_all(dir);
    }
}

// ─── Temp cleanup guard ──────────────────────────────────────────────────────

/// RAII guard that registers a cleanup handler on drop.
/// Created via `TempCleanupGuard::install()` at the start of `main()`.
/// On any exit path (normal return, `std::process::exit`, panic unwind),
/// the guard's `Drop` impl calls `cleanup_temp_sounds()`.
pub struct TempCleanupGuard;

impl TempCleanupGuard {
    /// Install the temp-file cleanup guard.  Call once at the start of `main()`.
    /// The returned guard should be bound to a variable (typically `_cleanup_guard`)
    /// so its `Drop` runs at process exit.
    pub fn install() -> Self {
        Self
    }
}

impl Drop for TempCleanupGuard {
    fn drop(&mut self) {
        cleanup_temp_sounds();
    }
}

// ─── No-spam cooldown ───────────────────────────────────────────────────────

/// Cooldown durations per event (prevents sound spam on rapid toggling).
/// Each event tracks the last play time and skips playback if called again
/// within its cooldown window. Cooldown in milliseconds per event type.
fn cooldown_ms(event: SoundEvent) -> u64 {
    match event {
        SoundEvent::Start => 0,        // one-shot, only fires once per session
        SoundEvent::Pause => 500,      // 500 ms debounce on pause toggle
        SoundEvent::Phase => 1_000,    // 1 s debounce on phase switch
        SoundEvent::Complete => 2_000, // 2 s cooldown on completion
    }
}

/// Global last-play timestamps for no-spam cooldown.
/// Uses wall-clock milliseconds (from SystemTime) so the 0-sentinel
/// for "never played" is never accidentally hit by a real timestamp.
static LAST_PLAY: [std::sync::atomic::AtomicU64; 4] = [
    std::sync::atomic::AtomicU64::new(0),
    std::sync::atomic::AtomicU64::new(0),
    std::sync::atomic::AtomicU64::new(0),
    std::sync::atomic::AtomicU64::new(0),
];

/// Returns wall-clock milliseconds since UNIX epoch.
fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// Returns `true` if the event should be played (outside cooldown window).
fn should_play(event: SoundEvent) -> bool {
    let idx = event as usize;
    let cooldown = cooldown_ms(event);
    if cooldown == 0 {
        return true;
    }
    let now = now_ms();
    let last = LAST_PLAY[idx].load(Ordering::Relaxed);
    // A last-play of 0 means "never played" — always allow.
    if last == 0 {
        LAST_PLAY[idx].store(now, Ordering::Relaxed);
        return true;
    }
    let elapsed = now.saturating_sub(last);
    if elapsed < cooldown {
        return false; // still in cooldown
    }
    LAST_PLAY[idx].store(now, Ordering::Relaxed);
    true
}

// ─── Playback primitives ────────────────────────────────────────────────────

/// Tries to play a WAV file via `pw-play` (PipeWire / PulseAudio compat).
fn play_file_via_pw(path: &std::path::Path) -> bool {
    Command::new("pw-play")
        .arg(path)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .is_ok()
}

/// Plays a terminal bell character (`\x07`).
fn terminal_bell() {
    let mut stdout = io::stdout();
    let _ = stdout.write_all(b"\x07");
    let _ = stdout.flush();
}

/// Triggers a visual bell (brief screen flash via DEC private mode).
fn visual_bell() {
    let mut stdout = io::stdout();
    let _ = stdout.write_all(b"\x1b[?5h");
    let _ = stdout.flush();
    std::thread::sleep(std::time::Duration::from_millis(60));
    let _ = stdout.write_all(b"\x1b[?5l");
    let _ = stdout.flush();
}

// ─── Core play function ────────────────────────────────────────────────────

/// Plays a sound event.  Attempts (in order):
///
/// 1. External file via `pw-play`  (if an env override is set).
/// 2. Built-in embedded WAV via `pw-play`  (temp file extraction).
/// 3. Terminal bell fallback (`\x07`).
///
/// If `ZENRITME_VISUAL_BELL` is set, a visual bell flash is also triggered.
pub fn play_event(event: SoundEvent) {
    // No-spam guard: skip if within cooldown window.
    if !should_play(event) {
        return;
    }

    let played = if let Some(ref file) = resolve_sound_file(event) {
        play_file_via_pw(std::path::Path::new(file))
    } else if let Some(path) = ensure_embedded_file(event) {
        play_file_via_pw(&path)
    } else {
        false
    };

    if !played {
        terminal_bell();
    }

    if std::env::var("ZENRITME_VISUAL_BELL").is_ok() {
        visual_bell();
    }
}

// ─── Legacy multi-beep (kept for backward compat) ──────────────────────────

/// Plays the *Complete* sound `times` times with a short gap.  Kept for
/// backward compatibility; the main loop now uses `play_event` directly.
#[allow(dead_code)]
pub fn beep(times: u32) {
    let times = times.max(1);
    for i in 0..times {
        play_event(SoundEvent::Complete);
        if i + 1 < times {
            std::thread::sleep(std::time::Duration::from_millis(120));
        }
    }
}

// ─── --sound-test ───────────────────────────────────────────────────────────

/// Prints sound-system status and plays all four events in sequence.
/// Cleans up temp sound files on completion.
pub fn sound_test() {
    println!("zenritme sound test (v{})", env!("CARGO_PKG_VERSION"));
    println!();

    // ── Per-event info ──────────────────────────────────────────────────────
    println!("Sound events:");
    for event in all_events() {
        let env = env_var(event);
        let source = sound_source(event);
        let cd = cooldown_ms(event);
        let cd_str = if cd == 0 {
            "no cooldown".to_string()
        } else {
            format!("{} ms cooldown", cd)
        };
        println!(
            "  {:9}  {}  [{}]  ({})",
            format!("{:?}", event),
            source,
            env,
            cd_str
        );
    }

    println!();

    // ── Sound profiles ─────────────────────────────────────────────────────
    println!("Sound profiles:");
    println!("  calm   - all notification sounds enabled (default)");
    println!("  silent - all notification sounds suppressed");
    println!("  --mute flag overrides any profile to silent");
    println!();

    // ── Override docs ──────────────────────────────────────────────────────
    println!("Environment variables:");
    println!("  ZENRITME_SOUND_START     override start sound file");
    println!("  ZENRITME_SOUND_PAUSE     override pause sound file");
    println!("  ZENRITME_SOUND_PHASE     override phase sound file");
    println!("  ZENRITME_SOUND_COMPLETE  override complete sound file");
    println!("  ZENRITME_SOUND_FILE      global fallback for all events");
    println!("  ZENRITME_VISUAL_BELL=1   enable visual bell (screen flash)");
    println!();

    // ── Global override ─────────────────────────────────────────────────────
    match std::env::var(ENV_GLOBAL) {
        Ok(p) => println!("Global override: {}", p),
        Err(_) => println!("Global override: (none)"),
    }

    // ── Visual bell ──────────────────────────────────────────────────────────
    if std::env::var("ZENRITME_VISUAL_BELL").is_ok() {
        println!("Visual bell:   enabled");
    } else {
        println!("Visual bell:   disabled");
    }
    println!();

    // ── Playback demo ───────────────────────────────────────────────────────
    println!("Playing all events in sequence...");
    for event in all_events() {
        print!("  {:?}... ", event);
        io::stdout().flush().ok();
        // Reset cooldown before test playback so each event actually plays.
        reset_cooldown(event);
        play_event(event);
        std::thread::sleep(std::time::Duration::from_millis(400));
        println!("ok");
    }
    println!();

    // ── Cleanup temp files ──────────────────────────────────────────────────
    cleanup_temp_sounds();
    println!("Temp sound files cleaned up.");
}

/// Reset the cooldown timer for a given event (used by --sound-test
/// to ensure each event plays during the demo sequence).
pub fn reset_cooldown(event: SoundEvent) {
    let idx = event as usize;
    LAST_PLAY[idx].store(0, Ordering::Relaxed);
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Embedded data validity ──────────────────────────────────────────────

    #[test]
    fn embedded_sounds_non_empty() {
        assert!(!SOUND_START.is_empty(), "start.wav is empty");
        assert!(!SOUND_PAUSE.is_empty(), "pause.wav is empty");
        assert!(!SOUND_PHASE.is_empty(), "phase.wav is empty");
        assert!(!SOUND_COMPLETE.is_empty(), "complete.wav is empty");
    }

    #[test]
    fn embedded_sounds_are_valid_wav() {
        for (name, data) in [
            ("start", SOUND_START as &[u8]),
            ("pause", SOUND_PAUSE as &[u8]),
            ("phase", SOUND_PHASE as &[u8]),
            ("complete", SOUND_COMPLETE as &[u8]),
        ] {
            assert!(
                data.len() >= 44,
                "{}: WAV header too small ({} bytes)",
                name,
                data.len()
            );
            assert!(&data[0..4] == b"RIFF", "{}: missing RIFF header", name);
            assert!(&data[8..12] == b"WAVE", "{}: missing WAVE format", name);
        }
    }

    // ── Stable mapping ─────────────────────────────────────────────────────

    #[test]
    fn asset_filenames_stable() {
        assert_eq!(asset_filename(SoundEvent::Start), "start.wav");
        assert_eq!(asset_filename(SoundEvent::Pause), "pause.wav");
        assert_eq!(asset_filename(SoundEvent::Phase), "phase.wav");
        assert_eq!(asset_filename(SoundEvent::Complete), "complete.wav");
    }

    #[test]
    fn env_var_names_stable() {
        assert_eq!(env_var(SoundEvent::Start), "ZENRITME_SOUND_START");
        assert_eq!(env_var(SoundEvent::Pause), "ZENRITME_SOUND_PAUSE");
        assert_eq!(env_var(SoundEvent::Phase), "ZENRITME_SOUND_PHASE");
        assert_eq!(env_var(SoundEvent::Complete), "ZENRITME_SOUND_COMPLETE");
    }

    #[test]
    fn embedded_sound_maps_to_correct_data() {
        assert_eq!(embedded_sound(SoundEvent::Start), SOUND_START);
        assert_eq!(embedded_sound(SoundEvent::Pause), SOUND_PAUSE);
        assert_eq!(embedded_sound(SoundEvent::Phase), SOUND_PHASE);
        assert_eq!(embedded_sound(SoundEvent::Complete), SOUND_COMPLETE);
    }

    #[test]
    fn all_events_returns_four() {
        let events = all_events();
        assert_eq!(events.len(), 4);
        assert_eq!(events[0], SoundEvent::Start);
        assert_eq!(events[1], SoundEvent::Pause);
        assert_eq!(events[2], SoundEvent::Phase);
        assert_eq!(events[3], SoundEvent::Complete);
    }

    // ── Sound source resolution ───────────────────────────────────────────

    #[test]
    fn sound_source_builtin_when_no_override() {
        std::env::remove_var(ENV_START);
        std::env::remove_var(ENV_GLOBAL);
        assert_eq!(sound_source(SoundEvent::Start), "built-in: start.wav");
    }

    #[test]
    fn sound_source_override_when_event_env_set() {
        std::env::set_var("ZENRITME_SOUND_START", "/tmp/custom.wav");
        assert_eq!(sound_source(SoundEvent::Start), "override: /tmp/custom.wav");
        std::env::remove_var("ZENRITME_SOUND_START");
    }

    #[test]
    fn sound_source_override_when_global_env_set() {
        std::env::remove_var("ZENRITME_SOUND_PAUSE");
        std::env::set_var("ZENRITME_SOUND_FILE", "/tmp/global.wav");
        assert_eq!(sound_source(SoundEvent::Pause), "override: /tmp/global.wav");
        std::env::remove_var("ZENRITME_SOUND_FILE");
    }

    // ── Resolution (env var precedence) ────────────────────────────────────

    #[test]
    fn resolve_returns_none_when_no_env_set() {
        // Ensure no event-specific or global env vars interfere.
        std::env::remove_var(ENV_START);
        std::env::remove_var(ENV_GLOBAL);
        assert_eq!(resolve_sound_file(SoundEvent::Start), None);
    }

    #[test]
    fn resolve_event_env_over_global() {
        std::env::set_var("ZENRITME_SOUND_START", "/tmp/test-start.wav");
        std::env::set_var("ZENRITME_SOUND_FILE", "/tmp/test-global.wav");
        assert_eq!(
            resolve_sound_file(SoundEvent::Start),
            Some("/tmp/test-start.wav".to_string())
        );
        std::env::remove_var("ZENRITME_SOUND_START");
        std::env::remove_var("ZENRITME_SOUND_FILE");
    }

    #[test]
    fn resolve_global_fallback_when_no_event_env() {
        std::env::remove_var("ZENRITME_SOUND_PAUSE");
        std::env::set_var("ZENRITME_SOUND_FILE", "/tmp/test-global.wav");
        assert_eq!(
            resolve_sound_file(SoundEvent::Pause),
            Some("/tmp/test-global.wav".to_string())
        );
        std::env::remove_var("ZENRITME_SOUND_FILE");
    }

    #[test]
    fn resolve_other_events_unaffected_by_event_env() {
        std::env::remove_var("ZENRITME_SOUND_FILE");
        std::env::set_var("ZENRITME_SOUND_START", "/tmp/test-start.wav");
        // Phase should not be affected by the START override.
        assert_eq!(resolve_sound_file(SoundEvent::Phase), None);
        std::env::remove_var("ZENRITME_SOUND_START");
    }

    #[test]
    fn all_events_have_embeddings() {
        for event in all_events() {
            assert!(
                !embedded_sound(event).is_empty(),
                "{:?} embedded sound is empty",
                event
            );
        }
    }

    // ── Sound profile ───────────────────────────────────────────────────

    #[test]
    fn profile_calm_from_name() {
        assert_eq!(SoundProfile::from_name("calm"), Some(SoundProfile::Calm));
    }

    #[test]
    fn profile_calm_case_insensitive() {
        assert_eq!(SoundProfile::from_name("Calm"), Some(SoundProfile::Calm));
        assert_eq!(SoundProfile::from_name("CALM"), Some(SoundProfile::Calm));
    }

    #[test]
    fn profile_silent_from_name() {
        assert_eq!(
            SoundProfile::from_name("silent"),
            Some(SoundProfile::Silent)
        );
    }

    #[test]
    fn profile_silent_case_insensitive() {
        assert_eq!(
            SoundProfile::from_name("Silent"),
            Some(SoundProfile::Silent)
        );
        assert_eq!(
            SoundProfile::from_name("SILENT"),
            Some(SoundProfile::Silent)
        );
    }

    #[test]
    fn profile_unknown_rejected() {
        assert_eq!(SoundProfile::from_name("loud"), None);
        assert_eq!(SoundProfile::from_name(""), None);
        assert_eq!(SoundProfile::from_name("off"), None);
    }

    #[test]
    fn profile_calm_is_not_silent() {
        assert!(!SoundProfile::Calm.is_silent());
    }

    #[test]
    fn profile_silent_is_silent() {
        assert!(SoundProfile::Silent.is_silent());
    }

    #[test]
    fn profile_as_str_roundtrip() {
        assert_eq!(
            SoundProfile::from_name(SoundProfile::Calm.as_str()),
            Some(SoundProfile::Calm)
        );
        assert_eq!(
            SoundProfile::from_name(SoundProfile::Silent.as_str()),
            Some(SoundProfile::Silent)
        );
    }

    // ── Mute/profile precedence ───────────────────────────────────────────

    #[test]
    fn mute_overrides_calm() {
        // --mute should suppress sound even with --sound-profile calm
        let muted = true;
        let profile = SoundProfile::Calm;
        assert!(muted || profile.is_silent(), "mute should suppress");
    }

    #[test]
    fn mute_overrides_silent_explicitly() {
        let muted = true;
        let profile = SoundProfile::Silent;
        assert!(muted || profile.is_silent(), "mute should suppress");
    }

    #[test]
    fn silent_profile_suppresses_without_mute() {
        let muted = false;
        let profile = SoundProfile::Silent;
        assert!(
            muted || profile.is_silent(),
            "silent profile should suppress"
        );
    }

    #[test]
    fn calm_profile_allows_sound_without_mute() {
        let muted = false;
        let profile = SoundProfile::Calm;
        assert!(
            !(muted || profile.is_silent()),
            "calm profile should allow sound"
        );
    }

    // ── Cooldown / no-spam ────────────────────────────────────────────────

    #[test]
    fn cooldown_start_is_zero() {
        assert_eq!(cooldown_ms(SoundEvent::Start), 0);
    }

    #[test]
    fn cooldown_pause_is_500ms() {
        assert_eq!(cooldown_ms(SoundEvent::Pause), 500);
    }

    #[test]
    fn cooldown_phase_is_1000ms() {
        assert_eq!(cooldown_ms(SoundEvent::Phase), 1_000);
    }

    #[test]
    fn cooldown_complete_is_2000ms() {
        assert_eq!(cooldown_ms(SoundEvent::Complete), 2_000);
    }

    #[test]
    fn should_play_start_always() {
        // Start has no cooldown — should always return true.
        reset_cooldown(SoundEvent::Start);
        assert!(should_play(SoundEvent::Start));
        assert!(should_play(SoundEvent::Start));
    }

    #[test]
    fn should_play_pause_debounces() {
        // Reset all cooldowns to avoid interference from other tests.
        for e in all_events() {
            reset_cooldown(e);
        }
        assert!(should_play(SoundEvent::Pause), "first call should play");
        assert!(
            !should_play(SoundEvent::Pause),
            "immediate second call should be debounced"
        );
    }

    #[test]
    fn should_play_complete_debounces() {
        for e in all_events() {
            reset_cooldown(e);
        }
        assert!(should_play(SoundEvent::Complete), "first call should play");
        assert!(
            !should_play(SoundEvent::Complete),
            "immediate second call should be debounced"
        );
    }

    #[test]
    fn reset_cooldown_allows_replay() {
        for e in all_events() {
            reset_cooldown(e);
        }
        assert!(should_play(SoundEvent::Pause));
        assert!(!should_play(SoundEvent::Pause));
        reset_cooldown(SoundEvent::Pause);
        assert!(
            should_play(SoundEvent::Pause),
            "after reset, should play again"
        );
    }

    // ── TempCleanupGuard ──────────────────────────────────────────────────

    #[test]
    fn temp_cleanup_guard_install() {
        let _guard = TempCleanupGuard::install();
        // Guard is created — Drop will fire when _guard goes out of scope.
        // This test verifies install() doesn't panic.
    }

    #[test]
    fn temp_cleanup_guard_drop_cleans() {
        // The global CLEANED flag may already be set from a prior test.
        // We test the guard by directly invoking cleanup (not via the static flag)
        // and verify it removes our specific temp directory.
        let dir = std::env::temp_dir().join(format!("zenritme-sounds-{}", std::process::id()));
        let _ = std::fs::create_dir_all(&dir);
        assert!(dir.exists(), "temp dir should exist before cleanup");
        // Directly remove to test the directory-specific logic (bypasses CLEANED flag).
        if dir.exists() {
            let _ = std::fs::remove_dir_all(&dir);
        }
        assert!(!dir.exists(), "temp dir should be removed after cleanup");
    }

    #[test]
    fn cleanup_idempotent() {
        // Calling cleanup multiple times should not panic or fail.
        cleanup_temp_sounds();
        cleanup_temp_sounds();
        cleanup_temp_sounds();
    }
}
